### ISSUE TITLE
IPv6 rollout

### ISSUE THREAD

**Issue by astro** [zentralwerk/network#3]
- [x] subnets
- [ ] sixxs upstream?
- [x] NAT66 trough `anon*`
- [x] container configuration
- [x] radvd on `gw*`
- [x] ospf6d in `core` net
- [ ] prefix delegation by vodafone?

**Comment by eri451** [comment]
ULA-Prefix: <code>fd23:42:c3d2:500::/56</code>

**Comment by hakunamenta** [comment]
ULAs are not supposed to look pretty.

**Comment by astro** [comment]
Ours do but is that a problem?

**Comment by hakunamenta** [comment]
if your definition of pretty is not unique, then the chance of collisions goes up.

**Comment by astro** [comment]
The prefix is unique in dn42. Go query the registry here: https://io.nixnodes.net/
