### ISSUE TITLE
mehrfache Belegung für ein Gerät an unterschiedlichen Switches?

### ISSUE THREAD

**Issue by yater** [zentralwerk/network#43]
`ap34` ist in salt-pillar/switches/init.sls mehrfach angegeben, einmal bei `switch-c1` ein witeres mal bei `switch-a1`.
theoretisch könnte es ja sein, dass das gerät anlassbezogen "wandert". dann könnte das einfach so "erklärt" werden. (anderenfalls machen sich ja menschen dazu gedanken, ob das so sein kann beziehungsweise soll.) damit wäre auch das issue hinfällig.)

**Comment by astro** [comment]
Dem ist sehr wahrscheinlich so: das ist mal gewandert.
